// compile with:
// protoc --go_out=. --go_opt=paths=source_relative multiview_demo.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: multiview_demo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Multicast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Reliable bool   `protobuf:"varint,2,opt,name=reliable,proto3" json:"reliable,omitempty"`
	Leafnum  uint32 `protobuf:"varint,3,opt,name=leafnum,proto3" json:"leafnum,omitempty"`
	Data     string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Multicast) Reset() {
	*x = Multicast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiview_demo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Multicast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Multicast) ProtoMessage() {}

func (x *Multicast) ProtoReflect() protoreflect.Message {
	mi := &file_multiview_demo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Multicast.ProtoReflect.Descriptor instead.
func (*Multicast) Descriptor() ([]byte, []int) {
	return file_multiview_demo_proto_rawDescGZIP(), []int{0}
}

func (x *Multicast) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Multicast) GetReliable() bool {
	if x != nil {
		return x.Reliable
	}
	return false
}

func (x *Multicast) GetLeafnum() uint32 {
	if x != nil {
		return x.Leafnum
	}
	return 0
}

func (x *Multicast) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_multiview_demo_proto protoreflect.FileDescriptor

var file_multiview_demo_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x64, 0x65, 0x6d, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a,
	0x09, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x63, 0x61, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x72, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65,
	0x61, 0x66, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6c, 0x65, 0x61,
	0x66, 0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x66, 0x6c, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x2f, 0x6c, 0x69, 0x62, 0x71, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_multiview_demo_proto_rawDescOnce sync.Once
	file_multiview_demo_proto_rawDescData = file_multiview_demo_proto_rawDesc
)

func file_multiview_demo_proto_rawDescGZIP() []byte {
	file_multiview_demo_proto_rawDescOnce.Do(func() {
		file_multiview_demo_proto_rawDescData = protoimpl.X.CompressGZIP(file_multiview_demo_proto_rawDescData)
	})
	return file_multiview_demo_proto_rawDescData
}

var file_multiview_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_multiview_demo_proto_goTypes = []interface{}{
	(*Multicast)(nil), // 0: proto.Multicast
}
var file_multiview_demo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_multiview_demo_proto_init() }
func file_multiview_demo_proto_init() {
	if File_multiview_demo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_multiview_demo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Multicast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_multiview_demo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multiview_demo_proto_goTypes,
		DependencyIndexes: file_multiview_demo_proto_depIdxs,
		MessageInfos:      file_multiview_demo_proto_msgTypes,
	}.Build()
	File_multiview_demo_proto = out.File
	file_multiview_demo_proto_rawDesc = nil
	file_multiview_demo_proto_goTypes = nil
	file_multiview_demo_proto_depIdxs = nil
}
