// compile with:
// protoc --go_out=. --go_opt=paths=source_relative mvdtext.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: mvdtext.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Serverdata *ServerData `protobuf:"bytes,1,opt,name=serverdata,proto3" json:"serverdata,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mvdtext_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_mvdtext_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_mvdtext_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetServerdata() *ServerData {
	if x != nil {
		return x.Serverdata
	}
	return nil
}

type ServerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Basestrings *BaseStrings `protobuf:"bytes,1,opt,name=basestrings,proto3" json:"basestrings,omitempty"`
}

func (x *ServerData) Reset() {
	*x = ServerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mvdtext_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerData) ProtoMessage() {}

func (x *ServerData) ProtoReflect() protoreflect.Message {
	mi := &file_mvdtext_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerData.ProtoReflect.Descriptor instead.
func (*ServerData) Descriptor() ([]byte, []int) {
	return file_mvdtext_proto_rawDescGZIP(), []int{1}
}

func (x *ServerData) GetBasestrings() *BaseStrings {
	if x != nil {
		return x.Basestrings
	}
	return nil
}

type BaseStrings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configstring []*ConfigString2 `protobuf:"bytes,1,rep,name=configstring,proto3" json:"configstring,omitempty"`
}

func (x *BaseStrings) Reset() {
	*x = BaseStrings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mvdtext_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseStrings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseStrings) ProtoMessage() {}

func (x *BaseStrings) ProtoReflect() protoreflect.Message {
	mi := &file_mvdtext_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseStrings.ProtoReflect.Descriptor instead.
func (*BaseStrings) Descriptor() ([]byte, []int) {
	return file_mvdtext_proto_rawDescGZIP(), []int{2}
}

func (x *BaseStrings) GetConfigstring() []*ConfigString2 {
	if x != nil {
		return x.Configstring
	}
	return nil
}

type ConfigString2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Str   string `protobuf:"bytes,2,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *ConfigString2) Reset() {
	*x = ConfigString2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mvdtext_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigString2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigString2) ProtoMessage() {}

func (x *ConfigString2) ProtoReflect() protoreflect.Message {
	mi := &file_mvdtext_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigString2.ProtoReflect.Descriptor instead.
func (*ConfigString2) Descriptor() ([]byte, []int) {
	return file_mvdtext_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigString2) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ConfigString2) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type MVDTextDemo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block []*Block `protobuf:"bytes,1,rep,name=block,proto3" json:"block,omitempty"`
}

func (x *MVDTextDemo) Reset() {
	*x = MVDTextDemo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mvdtext_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MVDTextDemo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MVDTextDemo) ProtoMessage() {}

func (x *MVDTextDemo) ProtoReflect() protoreflect.Message {
	mi := &file_mvdtext_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MVDTextDemo.ProtoReflect.Descriptor instead.
func (*MVDTextDemo) Descriptor() ([]byte, []int) {
	return file_mvdtext_proto_rawDescGZIP(), []int{4}
}

func (x *MVDTextDemo) GetBlock() []*Block {
	if x != nil {
		return x.Block
	}
	return nil
}

var File_mvdtext_proto protoreflect.FileDescriptor

var file_mvdtext_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x76, 0x64, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12,
	0x31, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x42, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x34, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x47, 0x0a, 0x0b, 0x42, 0x61, 0x73, 0x65, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x38, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x32, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22,
	0x37, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x32,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x22, 0x31, 0x0a, 0x0b, 0x4d, 0x56, 0x44, 0x54,
	0x65, 0x78, 0x74, 0x44, 0x65, 0x6d, 0x6f, 0x12, 0x22, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x26, 0x5a, 0x24, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x66, 0x6c, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x6c, 0x69, 0x62, 0x71, 0x32, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mvdtext_proto_rawDescOnce sync.Once
	file_mvdtext_proto_rawDescData = file_mvdtext_proto_rawDesc
)

func file_mvdtext_proto_rawDescGZIP() []byte {
	file_mvdtext_proto_rawDescOnce.Do(func() {
		file_mvdtext_proto_rawDescData = protoimpl.X.CompressGZIP(file_mvdtext_proto_rawDescData)
	})
	return file_mvdtext_proto_rawDescData
}

var file_mvdtext_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mvdtext_proto_goTypes = []interface{}{
	(*Block)(nil),         // 0: proto.Block
	(*ServerData)(nil),    // 1: proto.ServerData
	(*BaseStrings)(nil),   // 2: proto.BaseStrings
	(*ConfigString2)(nil), // 3: proto.ConfigString2
	(*MVDTextDemo)(nil),   // 4: proto.MVDTextDemo
}
var file_mvdtext_proto_depIdxs = []int32{
	1, // 0: proto.Block.serverdata:type_name -> proto.ServerData
	2, // 1: proto.ServerData.basestrings:type_name -> proto.BaseStrings
	3, // 2: proto.BaseStrings.configstring:type_name -> proto.ConfigString2
	0, // 3: proto.MVDTextDemo.block:type_name -> proto.Block
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mvdtext_proto_init() }
func file_mvdtext_proto_init() {
	if File_mvdtext_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mvdtext_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mvdtext_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mvdtext_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseStrings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mvdtext_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigString2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mvdtext_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MVDTextDemo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mvdtext_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mvdtext_proto_goTypes,
		DependencyIndexes: file_mvdtext_proto_depIdxs,
		MessageInfos:      file_mvdtext_proto_msgTypes,
	}.Build()
	File_mvdtext_proto = out.File
	file_mvdtext_proto_rawDesc = nil
	file_mvdtext_proto_goTypes = nil
	file_mvdtext_proto_depIdxs = nil
}
