// compile with:
// protoc --go_out=. --go_opt=paths=source_relative pak.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: pak.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a .pak file that contains other files
type PAKArchive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the particular pak file (including extension) ex: pak0.pak
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Just a description of what this archive is for
	Description []string `protobuf:"bytes,2,rep,name=description,proto3" json:"description,omitempty"`
	// All the files in the archive
	Files []*PAKFile `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *PAKArchive) Reset() {
	*x = PAKArchive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pak_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PAKArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAKArchive) ProtoMessage() {}

func (x *PAKArchive) ProtoReflect() protoreflect.Message {
	mi := &file_pak_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAKArchive.ProtoReflect.Descriptor instead.
func (*PAKArchive) Descriptor() ([]byte, []int) {
	return file_pak_proto_rawDescGZIP(), []int{0}
}

func (x *PAKArchive) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PAKArchive) GetDescription() []string {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *PAKArchive) GetFiles() []*PAKFile {
	if x != nil {
		return x.Files
	}
	return nil
}

// An individual file contained within a PAK archive
type PAKFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the name of the file in the archive. Ex: fart2.wav
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// the actual binary data
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PAKFile) Reset() {
	*x = PAKFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pak_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PAKFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAKFile) ProtoMessage() {}

func (x *PAKFile) ProtoReflect() protoreflect.Message {
	mi := &file_pak_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAKFile.ProtoReflect.Descriptor instead.
func (*PAKFile) Descriptor() ([]byte, []int) {
	return file_pak_proto_rawDescGZIP(), []int{1}
}

func (x *PAKFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PAKFile) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pak_proto protoreflect.FileDescriptor

var file_pak_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x61, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x68, 0x0a, 0x0a, 0x50, 0x41, 0x4b, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x41,
	0x4b, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x31, 0x0a, 0x07,
	0x50, 0x41, 0x4b, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42,
	0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x66, 0x6c, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x6c, 0x69, 0x62, 0x71,
	0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pak_proto_rawDescOnce sync.Once
	file_pak_proto_rawDescData = file_pak_proto_rawDesc
)

func file_pak_proto_rawDescGZIP() []byte {
	file_pak_proto_rawDescOnce.Do(func() {
		file_pak_proto_rawDescData = protoimpl.X.CompressGZIP(file_pak_proto_rawDescData)
	})
	return file_pak_proto_rawDescData
}

var file_pak_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pak_proto_goTypes = []interface{}{
	(*PAKArchive)(nil), // 0: proto.PAKArchive
	(*PAKFile)(nil),    // 1: proto.PAKFile
}
var file_pak_proto_depIdxs = []int32{
	1, // 0: proto.PAKArchive.files:type_name -> proto.PAKFile
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pak_proto_init() }
func file_pak_proto_init() {
	if File_pak_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pak_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PAKArchive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pak_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PAKFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pak_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pak_proto_goTypes,
		DependencyIndexes: file_pak_proto_depIdxs,
		MessageInfos:      file_pak_proto_msgTypes,
	}.Build()
	File_pak_proto = out.File
	file_pak_proto_rawDesc = nil
	file_pak_proto_goTypes = nil
	file_pak_proto_depIdxs = nil
}
