package bsp

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	bpb "github.com/packetflinger/libq2/proto/v1"
)

// noMaterialName mirrors TrenchBroom's own placeholder (BrushFace::
// NoMaterialName), used here for brush sides with no texinfo (texinfo
// index -1), which happens for compiler-added bevel planes that exist
// purely for collision and were never given a real texture.
const noMaterialName = "__TB_empty"

// Decompile converts a parsed BSPFile back into a Radiant-family .map
// source file in Quake2 "Valve" format, suitable for editing in
// TrenchBroom or (Net/Gtk)Radiant.
//
// Each dbrush_t becomes one editor brush built directly from its sides'
// planes and texinfo, so the emitted geometry always matches whatever the
// .bsp actually contains. The 3 points defining each face's plane are
// synthetic (see facePlanePoints) rather than the original mapper's
// vertices, which the compiled format doesn't retain - the editor
// recomputes the brush's real, bounded geometry itself as the
// intersection of all of a brush's face planes, so this doesn't affect
// the resulting shape.
func Decompile(bsp *bpb.BSPFile) (string, error) {
	modelBrushes, err := modelBrushIndices(bsp)
	if err != nil {
		return "", err
	}

	var sb strings.Builder
	sb.WriteString("// Game: Quake 2\n")
	sb.WriteString("// Format: Quake2 (Valve)\n")
	sb.WriteString("// Generator: libq2\n")

	for i, ent := range bsp.GetEntities() {
		modelIndex := -1
		if i == 0 {
			// The first entity is always the world entity, which owns
			// model 0 implicitly (it has no "model" property).
			modelIndex = 0
		} else if m, ok := ent.GetProperties()["model"]; ok && strings.HasPrefix(m, "*") {
			if n, err := strconv.Atoi(m[1:]); err == nil {
				modelIndex = n
			}
		}

		sb.WriteString("{\n")
		writeEntityProperties(&sb, ent)
		if brushes, ok := modelBrushes[int32(modelIndex)]; ok {
			for _, bi := range brushes {
				if err := writeBrush(&sb, bsp, bi); err != nil {
					return "", fmt.Errorf("entity %d (model %d), brush %d: %w", i, modelIndex, bi, err)
				}
			}
		}
		sb.WriteString("}\n")
	}

	return sb.String(), nil
}

// writeEntityProperties writes an entity's "key" "value" lines, classname
// first, the rest sorted for deterministic output. The stale "model"
// property is dropped: it names a submodel index from the .bsp being
// decompiled, which becomes meaningless (and is regenerated by whatever
// compiles the .map back down) once the brushes it pointed to are edited.
func writeEntityProperties(sb *strings.Builder, ent *bpb.BSPEntity) {
	props := ent.GetProperties()
	keys := make([]string, 0, len(props))
	for k := range props {
		if k == "classname" || k == "model" {
			continue
		}
		keys = append(keys, k)
	}
	sort.Strings(keys)

	if cn, ok := props["classname"]; ok {
		fmt.Fprintf(sb, "\"classname\" %s\n", quoteMapValue(cn))
	}
	for _, k := range keys {
		fmt.Fprintf(sb, "%s %s\n", quoteMapValue(k), quoteMapValue(props[k]))
	}
}

func quoteMapValue(s string) string {
	return "\"" + strings.ReplaceAll(s, `"`, `\"`) + "\""
}

// modelBrushIndices maps each model index to the sorted, deduplicated set
// of brush indices reachable from that model's BSP tree (headnode). A
// dmodel_t doesn't record its brushes directly - only a headnode - so
// this walks the tree down to its leaves, which each list the brushes
// relevant for collision there.
func modelBrushIndices(bsp *bpb.BSPFile) (map[int32][]int32, error) {
	result := make(map[int32][]int32, len(bsp.GetModels()))
	for i, m := range bsp.GetModels() {
		brushes, err := brushesForHeadNode(bsp, m.GetHeadNode())
		if err != nil {
			return nil, fmt.Errorf("model %d: %w", i, err)
		}
		result[int32(i)] = brushes
	}
	return result, nil
}

func brushesForHeadNode(bsp *bpb.BSPFile, headNode int32) ([]int32, error) {
	seen := map[int32]bool{}
	var brushes []int32

	var walk func(node int32) error
	walk = func(node int32) error {
		if node < 0 {
			leafIndex := -(node + 1)
			if leafIndex < 0 || int(leafIndex) >= len(bsp.GetLeaves()) {
				return fmt.Errorf("leaf index %d out of range (have %d leaves)", leafIndex, len(bsp.GetLeaves()))
			}
			leaf := bsp.GetLeaves()[leafIndex]
			for i := uint32(0); i < leaf.GetNumLeafBrushes(); i++ {
				idx := leaf.GetFirstLeafBrush() + i
				if int(idx) >= len(bsp.GetLeafBrushes()) {
					return fmt.Errorf("leaf brush table index %d out of range", idx)
				}
				b := int32(bsp.GetLeafBrushes()[idx])
				if !seen[b] {
					seen[b] = true
					brushes = append(brushes, b)
				}
			}
			return nil
		}
		if int(node) >= len(bsp.GetNodes()) {
			return fmt.Errorf("node index %d out of range (have %d nodes)", node, len(bsp.GetNodes()))
		}
		n := bsp.GetNodes()[node]
		if err := walk(n.GetFrontChild()); err != nil {
			return err
		}
		return walk(n.GetBackChild())
	}

	if err := walk(headNode); err != nil {
		return nil, err
	}
	sort.Slice(brushes, func(i, j int) bool { return brushes[i] < brushes[j] })
	return brushes, nil
}

func writeBrush(sb *strings.Builder, bsp *bpb.BSPFile, brushIndex int32) error {
	if brushIndex < 0 || int(brushIndex) >= len(bsp.GetBrushes()) {
		return fmt.Errorf("brush index %d out of range (have %d brushes)", brushIndex, len(bsp.GetBrushes()))
	}
	brush := bsp.GetBrushes()[brushIndex]

	sb.WriteString("{\n")
	for i := int32(0); i < brush.GetNumSides(); i++ {
		sideIdx := brush.GetFirstSide() + i
		if sideIdx < 0 || int(sideIdx) >= len(bsp.GetBrushSides()) {
			return fmt.Errorf("brush side index %d out of range (have %d)", sideIdx, len(bsp.GetBrushSides()))
		}
		if err := writeBrushSide(sb, bsp, bsp.GetBrushSides()[sideIdx], brush.GetContents()); err != nil {
			return err
		}
	}
	sb.WriteString("}\n")
	return nil
}

func writeBrushSide(sb *strings.Builder, bsp *bpb.BSPFile, side *bpb.BSPBrushSide, contents int32) error {
	planeNum := side.GetPlaneNum()
	if int(planeNum) >= len(bsp.GetPlanes()) {
		return fmt.Errorf("plane index %d out of range (have %d planes)", planeNum, len(bsp.GetPlanes()))
	}
	plane := bsp.GetPlanes()[planeNum]
	n := vec3{float64(plane.GetNormal().GetX()), float64(plane.GetNormal().GetY()), float64(plane.GetNormal().GetZ())}
	p0, p1, p2 := facePlanePoints(n, float64(plane.GetDistance()))

	material := noMaterialName
	sAxis, tAxis := arbitraryPerpendicular(n).normalize(), vec3{}
	tAxis = n.cross(sAxis)
	var sOffset, tOffset float64
	var flags, texValue int32

	if ti := side.GetTexinfo(); ti >= 0 {
		if int(ti) >= len(bsp.GetTextureInfo()) {
			return fmt.Errorf("texinfo index %d out of range (have %d)", ti, len(bsp.GetTextureInfo()))
		}
		t := bsp.GetTextureInfo()[ti]
		if name := t.GetTexture(); name != "" {
			material = name
		}
		sAxis = vec3{float64(t.GetSAxis().GetX()), float64(t.GetSAxis().GetY()), float64(t.GetSAxis().GetZ())}
		tAxis = vec3{float64(t.GetTAxis().GetX()), float64(t.GetTAxis().GetY()), float64(t.GetTAxis().GetZ())}
		sOffset = float64(t.GetSOffset())
		tOffset = float64(t.GetTOffset())
		flags = t.GetFlags()
		texValue = t.GetValue()
	}

	fmt.Fprintf(sb, "( %s ) ( %s ) ( %s ) %s [ %s %s %s %s ] [ %s %s %s %s ] 0 1 1 %d %d %d\n",
		formatVec(p0), formatVec(p1), formatVec(p2),
		quoteMaterial(material),
		formatNum(sAxis.x), formatNum(sAxis.y), formatNum(sAxis.z), formatNum(sOffset),
		formatNum(tAxis.x), formatNum(tAxis.y), formatNum(tAxis.z), formatNum(tOffset),
		contents, flags, texValue)
	return nil
}

func formatVec(v vec3) string {
	return formatNum(v.x) + " " + formatNum(v.y) + " " + formatNum(v.z)
}

func formatNum(v float64) string {
	return strconv.FormatFloat(v, 'g', -1, 64)
}

// quoteMaterial mirrors TrenchBroom's own quoting rule (Quake FileSerializer
// ::shouldQuoteMaterialName): quote only if empty or containing a
// character that would otherwise break tokenizing.
func quoteMaterial(name string) string {
	if name == "" {
		name = noMaterialName
	}
	if strings.ContainsAny(name, "\"\\ \t") {
		return "\"" + strings.ReplaceAll(name, `"`, `\"`) + "\""
	}
	return name
}
