// compile with:
// protoc --go_out=. --go_opt=paths=source_relative bsp.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: bsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A 3-dimensional float vector, used for normals, points, and origins.
type Vector3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{0}
}

func (x *Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// An axis-aligned bounding box.
type BoundingBox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mins *Vector3 `protobuf:"bytes,1,opt,name=mins,proto3" json:"mins,omitempty"`
	Maxs *Vector3 `protobuf:"bytes,2,opt,name=maxs,proto3" json:"maxs,omitempty"`
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{1}
}

func (x *BoundingBox) GetMins() *Vector3 {
	if x != nil {
		return x.Mins
	}
	return nil
}

func (x *BoundingBox) GetMaxs() *Vector3 {
	if x != nil {
		return x.Maxs
	}
	return nil
}

// Describes where a single lump lives within the file.
type BSPLump struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// byte offset from the start of the file
	Offset int32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// length of the lump in bytes
	Length int32 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *BSPLump) Reset() {
	*x = BSPLump{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPLump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPLump) ProtoMessage() {}

func (x *BSPLump) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPLump.ProtoReflect.Descriptor instead.
func (*BSPLump) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{2}
}

func (x *BSPLump) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BSPLump) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

// The fixed-size header at the start of every .bsp file.
type BSPHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// always "IBSP" (0x50534249)
	Magic int32 `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	// always 38 for Quake 2
	Version int32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// always 19 of these, one per lump
	Lumps []*BSPLump `protobuf:"bytes,3,rep,name=lumps,proto3" json:"lumps,omitempty"`
}

func (x *BSPHeader) Reset() {
	*x = BSPHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPHeader) ProtoMessage() {}

func (x *BSPHeader) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPHeader.ProtoReflect.Descriptor instead.
func (*BSPHeader) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{3}
}

func (x *BSPHeader) GetMagic() int32 {
	if x != nil {
		return x.Magic
	}
	return 0
}

func (x *BSPHeader) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BSPHeader) GetLumps() []*BSPLump {
	if x != nil {
		return x.Lumps
	}
	return nil
}

// A single map entity (player starts, items, triggers, lights, etc).
type BSPEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// convenience copy of the "classname" property
	ClassName string `protobuf:"bytes,1,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	// all key/value pairs defined for this entity
	Properties map[string]string `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BSPEntity) Reset() {
	*x = BSPEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPEntity) ProtoMessage() {}

func (x *BSPEntity) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPEntity.ProtoReflect.Descriptor instead.
func (*BSPEntity) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{4}
}

func (x *BSPEntity) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *BSPEntity) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// A plane used to split the world for BSP nodes, faces, and brush sides.
type BSPPlane struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Normal   *Vector3 `protobuf:"bytes,1,opt,name=normal,proto3" json:"normal,omitempty"`
	Distance float32  `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	// PLANE_X, PLANE_Y, PLANE_Z, PLANE_ANYX, PLANE_ANYY, or PLANE_ANYZ
	Type int32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *BSPPlane) Reset() {
	*x = BSPPlane{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPPlane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPPlane) ProtoMessage() {}

func (x *BSPPlane) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPPlane.ProtoReflect.Descriptor instead.
func (*BSPPlane) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{5}
}

func (x *BSPPlane) GetNormal() *Vector3 {
	if x != nil {
		return x.Normal
	}
	return nil
}

func (x *BSPPlane) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *BSPPlane) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// A single point in 3D space.
type BSPVertex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Point *Vector3 `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
}

func (x *BSPVertex) Reset() {
	*x = BSPVertex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPVertex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPVertex) ProtoMessage() {}

func (x *BSPVertex) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPVertex.ProtoReflect.Descriptor instead.
func (*BSPVertex) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{6}
}

func (x *BSPVertex) GetPoint() *Vector3 {
	if x != nil {
		return x.Point
	}
	return nil
}

// Byte offsets into the visibility bit vectors for one cluster.
type BSPVisOffset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// offset to this cluster's potentially visible set
	Pvs int32 `protobuf:"varint,1,opt,name=pvs,proto3" json:"pvs,omitempty"`
	// offset to this cluster's potentially hearable set
	Phs int32 `protobuf:"varint,2,opt,name=phs,proto3" json:"phs,omitempty"`
}

func (x *BSPVisOffset) Reset() {
	*x = BSPVisOffset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPVisOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPVisOffset) ProtoMessage() {}

func (x *BSPVisOffset) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPVisOffset.ProtoReflect.Descriptor instead.
func (*BSPVisOffset) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{7}
}

func (x *BSPVisOffset) GetPvs() int32 {
	if x != nil {
		return x.Pvs
	}
	return 0
}

func (x *BSPVisOffset) GetPhs() int32 {
	if x != nil {
		return x.Phs
	}
	return 0
}

// The visibility lump: run-length-encoded bit vectors describing which
// clusters are visible/audible from which other clusters.
type BSPVisibility struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterCount int32           `protobuf:"varint,1,opt,name=cluster_count,json=clusterCount,proto3" json:"cluster_count,omitempty"`
	Offsets      []*BSPVisOffset `protobuf:"bytes,2,rep,name=offsets,proto3" json:"offsets,omitempty"`
	// raw RLE-encoded vis bit vectors referenced by the offsets above
	BitVectors []byte `protobuf:"bytes,3,opt,name=bit_vectors,json=bitVectors,proto3" json:"bit_vectors,omitempty"`
}

func (x *BSPVisibility) Reset() {
	*x = BSPVisibility{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPVisibility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPVisibility) ProtoMessage() {}

func (x *BSPVisibility) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPVisibility.ProtoReflect.Descriptor instead.
func (*BSPVisibility) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{8}
}

func (x *BSPVisibility) GetClusterCount() int32 {
	if x != nil {
		return x.ClusterCount
	}
	return 0
}

func (x *BSPVisibility) GetOffsets() []*BSPVisOffset {
	if x != nil {
		return x.Offsets
	}
	return nil
}

func (x *BSPVisibility) GetBitVectors() []byte {
	if x != nil {
		return x.BitVectors
	}
	return nil
}

// A node in the BSP tree.
type BSPNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaneNum int32 `protobuf:"varint,1,opt,name=plane_num,json=planeNum,proto3" json:"plane_num,omitempty"`
	// negative values are -(leaf_index + 1) rather than a node index
	FrontChild int32        `protobuf:"varint,2,opt,name=front_child,json=frontChild,proto3" json:"front_child,omitempty"`
	BackChild  int32        `protobuf:"varint,3,opt,name=back_child,json=backChild,proto3" json:"back_child,omitempty"`
	Bounds     *BoundingBox `protobuf:"bytes,4,opt,name=bounds,proto3" json:"bounds,omitempty"`
	FirstFace  uint32       `protobuf:"varint,5,opt,name=first_face,json=firstFace,proto3" json:"first_face,omitempty"`
	NumFaces   uint32       `protobuf:"varint,6,opt,name=num_faces,json=numFaces,proto3" json:"num_faces,omitempty"`
}

func (x *BSPNode) Reset() {
	*x = BSPNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPNode) ProtoMessage() {}

func (x *BSPNode) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPNode.ProtoReflect.Descriptor instead.
func (*BSPNode) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{9}
}

func (x *BSPNode) GetPlaneNum() int32 {
	if x != nil {
		return x.PlaneNum
	}
	return 0
}

func (x *BSPNode) GetFrontChild() int32 {
	if x != nil {
		return x.FrontChild
	}
	return 0
}

func (x *BSPNode) GetBackChild() int32 {
	if x != nil {
		return x.BackChild
	}
	return 0
}

func (x *BSPNode) GetBounds() *BoundingBox {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *BSPNode) GetFirstFace() uint32 {
	if x != nil {
		return x.FirstFace
	}
	return 0
}

func (x *BSPNode) GetNumFaces() uint32 {
	if x != nil {
		return x.NumFaces
	}
	return 0
}

// Texture placement/orientation info, shared by one or more faces.
type BSPTexInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SAxis   *Vector3 `protobuf:"bytes,1,opt,name=s_axis,json=sAxis,proto3" json:"s_axis,omitempty"`
	SOffset float32  `protobuf:"fixed32,2,opt,name=s_offset,json=sOffset,proto3" json:"s_offset,omitempty"`
	TAxis   *Vector3 `protobuf:"bytes,3,opt,name=t_axis,json=tAxis,proto3" json:"t_axis,omitempty"`
	TOffset float32  `protobuf:"fixed32,4,opt,name=t_offset,json=tOffset,proto3" json:"t_offset,omitempty"`
	// SURF_* bitflags (light, slick, sky, warp, trans33, trans66, flowing, nodraw...)
	Flags int32 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	// light emission value, for surfaces that emit light
	Value int32 `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
	// texture name (max 32 chars), no path prefix or extension
	Texture string `protobuf:"bytes,7,opt,name=texture,proto3" json:"texture,omitempty"`
	// for animated textures, index of the next frame; -1 if none
	NextTexinfo int32 `protobuf:"varint,8,opt,name=next_texinfo,json=nextTexinfo,proto3" json:"next_texinfo,omitempty"`
}

func (x *BSPTexInfo) Reset() {
	*x = BSPTexInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPTexInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPTexInfo) ProtoMessage() {}

func (x *BSPTexInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPTexInfo.ProtoReflect.Descriptor instead.
func (*BSPTexInfo) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{10}
}

func (x *BSPTexInfo) GetSAxis() *Vector3 {
	if x != nil {
		return x.SAxis
	}
	return nil
}

func (x *BSPTexInfo) GetSOffset() float32 {
	if x != nil {
		return x.SOffset
	}
	return 0
}

func (x *BSPTexInfo) GetTAxis() *Vector3 {
	if x != nil {
		return x.TAxis
	}
	return nil
}

func (x *BSPTexInfo) GetTOffset() float32 {
	if x != nil {
		return x.TOffset
	}
	return 0
}

func (x *BSPTexInfo) GetFlags() int32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *BSPTexInfo) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *BSPTexInfo) GetTexture() string {
	if x != nil {
		return x.Texture
	}
	return ""
}

func (x *BSPTexInfo) GetNextTexinfo() int32 {
	if x != nil {
		return x.NextTexinfo
	}
	return 0
}

// A single planar surface made up of edges.
type BSPFace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaneNum uint32 `protobuf:"varint,1,opt,name=plane_num,json=planeNum,proto3" json:"plane_num,omitempty"`
	// 0 = front of plane, 1 = back of plane
	Side int32 `protobuf:"varint,2,opt,name=side,proto3" json:"side,omitempty"`
	// index into the surfedges table
	FirstEdge int32 `protobuf:"varint,3,opt,name=first_edge,json=firstEdge,proto3" json:"first_edge,omitempty"`
	NumEdges  int32 `protobuf:"varint,4,opt,name=num_edges,json=numEdges,proto3" json:"num_edges,omitempty"`
	Texinfo   int32 `protobuf:"varint,5,opt,name=texinfo,proto3" json:"texinfo,omitempty"`
	// up to 4 lightmap style indices
	LightStyles []uint32 `protobuf:"varint,6,rep,packed,name=light_styles,json=lightStyles,proto3" json:"light_styles,omitempty"`
	// offset into the lighting lump; -1 if this face isn't lit
	LightOffset int32 `protobuf:"varint,7,opt,name=light_offset,json=lightOffset,proto3" json:"light_offset,omitempty"`
}

func (x *BSPFace) Reset() {
	*x = BSPFace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPFace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPFace) ProtoMessage() {}

func (x *BSPFace) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPFace.ProtoReflect.Descriptor instead.
func (*BSPFace) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{11}
}

func (x *BSPFace) GetPlaneNum() uint32 {
	if x != nil {
		return x.PlaneNum
	}
	return 0
}

func (x *BSPFace) GetSide() int32 {
	if x != nil {
		return x.Side
	}
	return 0
}

func (x *BSPFace) GetFirstEdge() int32 {
	if x != nil {
		return x.FirstEdge
	}
	return 0
}

func (x *BSPFace) GetNumEdges() int32 {
	if x != nil {
		return x.NumEdges
	}
	return 0
}

func (x *BSPFace) GetTexinfo() int32 {
	if x != nil {
		return x.Texinfo
	}
	return 0
}

func (x *BSPFace) GetLightStyles() []uint32 {
	if x != nil {
		return x.LightStyles
	}
	return nil
}

func (x *BSPFace) GetLightOffset() int32 {
	if x != nil {
		return x.LightOffset
	}
	return 0
}

// A leaf node of the BSP tree; leaves are where the actual geometry and
// visibility/collision data live.
type BSPLeaf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// CONTENTS_* bitflags (solid, water, lava, slime, etc)
	Contents int32 `protobuf:"varint,1,opt,name=contents,proto3" json:"contents,omitempty"`
	// -1 if this leaf has no visibility info
	Cluster        int32        `protobuf:"varint,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Area           int32        `protobuf:"varint,3,opt,name=area,proto3" json:"area,omitempty"`
	Bounds         *BoundingBox `protobuf:"bytes,4,opt,name=bounds,proto3" json:"bounds,omitempty"`
	FirstLeafFace  uint32       `protobuf:"varint,5,opt,name=first_leaf_face,json=firstLeafFace,proto3" json:"first_leaf_face,omitempty"`
	NumLeafFaces   uint32       `protobuf:"varint,6,opt,name=num_leaf_faces,json=numLeafFaces,proto3" json:"num_leaf_faces,omitempty"`
	FirstLeafBrush uint32       `protobuf:"varint,7,opt,name=first_leaf_brush,json=firstLeafBrush,proto3" json:"first_leaf_brush,omitempty"`
	NumLeafBrushes uint32       `protobuf:"varint,8,opt,name=num_leaf_brushes,json=numLeafBrushes,proto3" json:"num_leaf_brushes,omitempty"`
}

func (x *BSPLeaf) Reset() {
	*x = BSPLeaf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPLeaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPLeaf) ProtoMessage() {}

func (x *BSPLeaf) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPLeaf.ProtoReflect.Descriptor instead.
func (*BSPLeaf) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{12}
}

func (x *BSPLeaf) GetContents() int32 {
	if x != nil {
		return x.Contents
	}
	return 0
}

func (x *BSPLeaf) GetCluster() int32 {
	if x != nil {
		return x.Cluster
	}
	return 0
}

func (x *BSPLeaf) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *BSPLeaf) GetBounds() *BoundingBox {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *BSPLeaf) GetFirstLeafFace() uint32 {
	if x != nil {
		return x.FirstLeafFace
	}
	return 0
}

func (x *BSPLeaf) GetNumLeafFaces() uint32 {
	if x != nil {
		return x.NumLeafFaces
	}
	return 0
}

func (x *BSPLeaf) GetFirstLeafBrush() uint32 {
	if x != nil {
		return x.FirstLeafBrush
	}
	return 0
}

func (x *BSPLeaf) GetNumLeafBrushes() uint32 {
	if x != nil {
		return x.NumLeafBrushes
	}
	return 0
}

// An edge connecting two vertices, referenced by faces via surfedges.
type BSPEdge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vertex1 uint32 `protobuf:"varint,1,opt,name=vertex1,proto3" json:"vertex1,omitempty"`
	Vertex2 uint32 `protobuf:"varint,2,opt,name=vertex2,proto3" json:"vertex2,omitempty"`
}

func (x *BSPEdge) Reset() {
	*x = BSPEdge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPEdge) ProtoMessage() {}

func (x *BSPEdge) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPEdge.ProtoReflect.Descriptor instead.
func (*BSPEdge) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{13}
}

func (x *BSPEdge) GetVertex1() uint32 {
	if x != nil {
		return x.Vertex1
	}
	return 0
}

func (x *BSPEdge) GetVertex2() uint32 {
	if x != nil {
		return x.Vertex2
	}
	return 0
}

// A rigid group of brushes/faces, either the world itself (model 0) or an
// inline brush model referenced by an entity.
type BSPModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bounds *BoundingBox `protobuf:"bytes,1,opt,name=bounds,proto3" json:"bounds,omitempty"`
	// used for rotating brush models
	Origin    *Vector3 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	HeadNode  int32    `protobuf:"varint,3,opt,name=head_node,json=headNode,proto3" json:"head_node,omitempty"`
	FirstFace int32    `protobuf:"varint,4,opt,name=first_face,json=firstFace,proto3" json:"first_face,omitempty"`
	NumFaces  int32    `protobuf:"varint,5,opt,name=num_faces,json=numFaces,proto3" json:"num_faces,omitempty"`
}

func (x *BSPModel) Reset() {
	*x = BSPModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPModel) ProtoMessage() {}

func (x *BSPModel) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPModel.ProtoReflect.Descriptor instead.
func (*BSPModel) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{14}
}

func (x *BSPModel) GetBounds() *BoundingBox {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *BSPModel) GetOrigin() *Vector3 {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *BSPModel) GetHeadNode() int32 {
	if x != nil {
		return x.HeadNode
	}
	return 0
}

func (x *BSPModel) GetFirstFace() int32 {
	if x != nil {
		return x.FirstFace
	}
	return 0
}

func (x *BSPModel) GetNumFaces() int32 {
	if x != nil {
		return x.NumFaces
	}
	return 0
}

// A convex volume made of planes (brush sides), used for collision.
type BSPBrush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstSide int32 `protobuf:"varint,1,opt,name=first_side,json=firstSide,proto3" json:"first_side,omitempty"`
	NumSides  int32 `protobuf:"varint,2,opt,name=num_sides,json=numSides,proto3" json:"num_sides,omitempty"`
	// CONTENTS_* bitflags
	Contents int32 `protobuf:"varint,3,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *BSPBrush) Reset() {
	*x = BSPBrush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPBrush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPBrush) ProtoMessage() {}

func (x *BSPBrush) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPBrush.ProtoReflect.Descriptor instead.
func (*BSPBrush) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{15}
}

func (x *BSPBrush) GetFirstSide() int32 {
	if x != nil {
		return x.FirstSide
	}
	return 0
}

func (x *BSPBrush) GetNumSides() int32 {
	if x != nil {
		return x.NumSides
	}
	return 0
}

func (x *BSPBrush) GetContents() int32 {
	if x != nil {
		return x.Contents
	}
	return 0
}

// One plane bounding a brush.
type BSPBrushSide struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaneNum uint32 `protobuf:"varint,1,opt,name=plane_num,json=planeNum,proto3" json:"plane_num,omitempty"`
	// -1 if this side has no texture
	Texinfo int32 `protobuf:"varint,2,opt,name=texinfo,proto3" json:"texinfo,omitempty"`
}

func (x *BSPBrushSide) Reset() {
	*x = BSPBrushSide{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPBrushSide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPBrushSide) ProtoMessage() {}

func (x *BSPBrushSide) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPBrushSide.ProtoReflect.Descriptor instead.
func (*BSPBrushSide) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{16}
}

func (x *BSPBrushSide) GetPlaneNum() uint32 {
	if x != nil {
		return x.PlaneNum
	}
	return 0
}

func (x *BSPBrushSide) GetTexinfo() int32 {
	if x != nil {
		return x.Texinfo
	}
	return 0
}

// Areas are large-scale visibility/sound regions connected by area portals
// (e.g. separate rooms connected by a door).
type BSPArea struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumAreaPortals  int32 `protobuf:"varint,1,opt,name=num_area_portals,json=numAreaPortals,proto3" json:"num_area_portals,omitempty"`
	FirstAreaPortal int32 `protobuf:"varint,2,opt,name=first_area_portal,json=firstAreaPortal,proto3" json:"first_area_portal,omitempty"`
}

func (x *BSPArea) Reset() {
	*x = BSPArea{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPArea) ProtoMessage() {}

func (x *BSPArea) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPArea.ProtoReflect.Descriptor instead.
func (*BSPArea) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{17}
}

func (x *BSPArea) GetNumAreaPortals() int32 {
	if x != nil {
		return x.NumAreaPortals
	}
	return 0
}

func (x *BSPArea) GetFirstAreaPortal() int32 {
	if x != nil {
		return x.FirstAreaPortal
	}
	return 0
}

// A portal connecting two areas, opened/closed via func_areaportal entities.
type BSPAreaPortal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PortalNum int32 `protobuf:"varint,1,opt,name=portal_num,json=portalNum,proto3" json:"portal_num,omitempty"`
	OtherArea int32 `protobuf:"varint,2,opt,name=other_area,json=otherArea,proto3" json:"other_area,omitempty"`
}

func (x *BSPAreaPortal) Reset() {
	*x = BSPAreaPortal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPAreaPortal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPAreaPortal) ProtoMessage() {}

func (x *BSPAreaPortal) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPAreaPortal.ProtoReflect.Descriptor instead.
func (*BSPAreaPortal) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{18}
}

func (x *BSPAreaPortal) GetPortalNum() int32 {
	if x != nil {
		return x.PortalNum
	}
	return 0
}

func (x *BSPAreaPortal) GetOtherArea() int32 {
	if x != nil {
		return x.OtherArea
	}
	return 0
}

// The complete contents of a Quake 2 .bsp map file.
type BSPFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// just the filename minus extension, ex: "q2dm1"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// including any path prefix and .bsp extension
	Filename string     `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Header   *BSPHeader `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	// lump 0: entity definitions, stored as a single text blob in the file
	Entities []*BSPEntity `protobuf:"bytes,4,rep,name=entities,proto3" json:"entities,omitempty"`
	// lump 1
	Planes []*BSPPlane `protobuf:"bytes,5,rep,name=planes,proto3" json:"planes,omitempty"`
	// lump 2
	Vertices []*BSPVertex `protobuf:"bytes,6,rep,name=vertices,proto3" json:"vertices,omitempty"`
	// lump 3
	Visibility *BSPVisibility `protobuf:"bytes,7,opt,name=visibility,proto3" json:"visibility,omitempty"`
	// lump 4
	Nodes []*BSPNode `protobuf:"bytes,8,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// lump 5 (LUMP_TEXINFO)
	TextureInfo []*BSPTexInfo `protobuf:"bytes,9,rep,name=texture_info,json=textureInfo,proto3" json:"texture_info,omitempty"`
	// lump 6
	Faces []*BSPFace `protobuf:"bytes,10,rep,name=faces,proto3" json:"faces,omitempty"`
	// lump 7: raw lightmap data referenced by BSPFace.light_offset
	Lighting []byte `protobuf:"bytes,11,opt,name=lighting,proto3" json:"lighting,omitempty"`
	// lump 8
	Leaves []*BSPLeaf `protobuf:"bytes,12,rep,name=leaves,proto3" json:"leaves,omitempty"`
	// lump 9: indices into faces, referenced by leaves
	LeafFaces []uint32 `protobuf:"varint,13,rep,packed,name=leaf_faces,json=leafFaces,proto3" json:"leaf_faces,omitempty"`
	// lump 10: indices into brushes, referenced by leaves
	LeafBrushes []uint32 `protobuf:"varint,14,rep,packed,name=leaf_brushes,json=leafBrushes,proto3" json:"leaf_brushes,omitempty"`
	// lump 11
	Edges []*BSPEdge `protobuf:"bytes,15,rep,name=edges,proto3" json:"edges,omitempty"`
	// lump 12: signed indices into edges; negative means traverse the edge
	// vertex2 -> vertex1 instead of vertex1 -> vertex2
	SurfEdges []int32 `protobuf:"varint,16,rep,packed,name=surf_edges,json=surfEdges,proto3" json:"surf_edges,omitempty"`
	// lump 13: model 0 is always the world itself
	Models []*BSPModel `protobuf:"bytes,17,rep,name=models,proto3" json:"models,omitempty"`
	// lump 14
	Brushes []*BSPBrush `protobuf:"bytes,18,rep,name=brushes,proto3" json:"brushes,omitempty"`
	// lump 15
	BrushSides []*BSPBrushSide `protobuf:"bytes,19,rep,name=brush_sides,json=brushSides,proto3" json:"brush_sides,omitempty"`
	// lump 16: potentially visible set decompression table (unused by id software's tools)
	Pop []byte `protobuf:"bytes,20,opt,name=pop,proto3" json:"pop,omitempty"`
	// lump 17
	Areas []*BSPArea `protobuf:"bytes,21,rep,name=areas,proto3" json:"areas,omitempty"`
	// lump 18
	AreaPortals []*BSPAreaPortal `protobuf:"bytes,22,rep,name=area_portals,json=areaPortals,proto3" json:"area_portals,omitempty"`
}

func (x *BSPFile) Reset() {
	*x = BSPFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPFile) ProtoMessage() {}

func (x *BSPFile) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPFile.ProtoReflect.Descriptor instead.
func (*BSPFile) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{19}
}

func (x *BSPFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BSPFile) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *BSPFile) GetHeader() *BSPHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BSPFile) GetEntities() []*BSPEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *BSPFile) GetPlanes() []*BSPPlane {
	if x != nil {
		return x.Planes
	}
	return nil
}

func (x *BSPFile) GetVertices() []*BSPVertex {
	if x != nil {
		return x.Vertices
	}
	return nil
}

func (x *BSPFile) GetVisibility() *BSPVisibility {
	if x != nil {
		return x.Visibility
	}
	return nil
}

func (x *BSPFile) GetNodes() []*BSPNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *BSPFile) GetTextureInfo() []*BSPTexInfo {
	if x != nil {
		return x.TextureInfo
	}
	return nil
}

func (x *BSPFile) GetFaces() []*BSPFace {
	if x != nil {
		return x.Faces
	}
	return nil
}

func (x *BSPFile) GetLighting() []byte {
	if x != nil {
		return x.Lighting
	}
	return nil
}

func (x *BSPFile) GetLeaves() []*BSPLeaf {
	if x != nil {
		return x.Leaves
	}
	return nil
}

func (x *BSPFile) GetLeafFaces() []uint32 {
	if x != nil {
		return x.LeafFaces
	}
	return nil
}

func (x *BSPFile) GetLeafBrushes() []uint32 {
	if x != nil {
		return x.LeafBrushes
	}
	return nil
}

func (x *BSPFile) GetEdges() []*BSPEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *BSPFile) GetSurfEdges() []int32 {
	if x != nil {
		return x.SurfEdges
	}
	return nil
}

func (x *BSPFile) GetModels() []*BSPModel {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *BSPFile) GetBrushes() []*BSPBrush {
	if x != nil {
		return x.Brushes
	}
	return nil
}

func (x *BSPFile) GetBrushSides() []*BSPBrushSide {
	if x != nil {
		return x.BrushSides
	}
	return nil
}

func (x *BSPFile) GetPop() []byte {
	if x != nil {
		return x.Pop
	}
	return nil
}

func (x *BSPFile) GetAreas() []*BSPArea {
	if x != nil {
		return x.Areas
	}
	return nil
}

func (x *BSPFile) GetAreaPortals() []*BSPAreaPortal {
	if x != nil {
		return x.AreaPortals
	}
	return nil
}

// An r1q2 ".override" sidecar file (conventionally named
// "<mapname>.bsp.override"), which lets a server transparently redirect
// clients to a different .bsp, report a specific checksum instead of
// computing one from the loaded file, and/or replace the entity string
// without modifying the .bsp itself. See CM_LoadMap in
// https://github.com/tastyspleen/r1q2-archive/blob/master/qcommon/cmodel.c
type BSPOverride struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// replacement .bsp filename the server should actually load instead of
	// the one requested, ex: "maps/q2dm1.bsp" (max 63 chars). Unset means
	// no redirect.
	MapName *string `protobuf:"bytes,1,opt,name=map_name,json=mapName,proto3,oneof" json:"map_name,omitempty"`
	// checksum to report to clients instead of computing one from the
	// loaded file. Unset means compute it normally.
	Checksum *uint32 `protobuf:"varint,2,opt,name=checksum,proto3,oneof" json:"checksum,omitempty"`
	// entity definitions to use instead of whatever's baked into the
	// loaded .bsp's own entity lump. Empty means use the .bsp's own.
	Entities []*BSPEntity `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *BSPOverride) Reset() {
	*x = BSPOverride{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsp_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSPOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPOverride) ProtoMessage() {}

func (x *BSPOverride) ProtoReflect() protoreflect.Message {
	mi := &file_bsp_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPOverride.ProtoReflect.Descriptor instead.
func (*BSPOverride) Descriptor() ([]byte, []int) {
	return file_bsp_proto_rawDescGZIP(), []int{20}
}

func (x *BSPOverride) GetMapName() string {
	if x != nil && x.MapName != nil {
		return *x.MapName
	}
	return ""
}

func (x *BSPOverride) GetChecksum() uint32 {
	if x != nil && x.Checksum != nil {
		return *x.Checksum
	}
	return 0
}

func (x *BSPOverride) GetEntities() []*BSPEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

var File_bsp_proto protoreflect.FileDescriptor

var file_bsp_proto_rawDesc = []byte{
	0x0a, 0x09, 0x62, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x76, 0x31, 0x22, 0x33, 0x0a, 0x07, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01,
	0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x5b, 0x0a, 0x0b, 0x42, 0x6f,
	0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x78, 0x12, 0x25, 0x0a, 0x04, 0x6d, 0x69, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x73,
	0x12, 0x25, 0x0a, 0x04, 0x6d, 0x61, 0x78, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x33, 0x52, 0x04, 0x6d, 0x61, 0x78, 0x73, 0x22, 0x39, 0x0a, 0x07, 0x42, 0x53, 0x50, 0x4c, 0x75,
	0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x22, 0x64, 0x0a, 0x09, 0x42, 0x53, 0x50, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6d, 0x61, 0x67, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x27, 0x0a, 0x05, 0x6c, 0x75, 0x6d, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x53, 0x50, 0x4c, 0x75, 0x6d,
	0x70, 0x52, 0x05, 0x6c, 0x75, 0x6d, 0x70, 0x73, 0x22, 0xae, 0x01, 0x0a, 0x09, 0x42, 0x53, 0x50,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x53, 0x50, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x65, 0x0a, 0x08, 0x42, 0x53, 0x50,
	0x50, 0x6c, 0x61, 0x6e, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x52, 0x06, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x34, 0x0a, 0x09, 0x42, 0x53, 0x50, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x12, 0x27, 0x0a,
	0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x52,
	0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x32, 0x0a, 0x0c, 0x42, 0x53, 0x50, 0x56, 0x69, 0x73,
	0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x76, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x76, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x68, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x68, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x0d, 0x42,
	0x53, 0x50, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x0d,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x30, 0x0a, 0x07, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x53,
	0x50, 0x56, 0x69, 0x73, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x52, 0x07, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x69, 0x74, 0x5f, 0x76, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x62, 0x69, 0x74, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x73, 0x22, 0xd1, 0x01, 0x0a, 0x07, 0x42, 0x53, 0x50, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1f, 0x0a,
	0x0b, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x62, 0x61, 0x63, 0x6b, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x12, 0x2d, 0x0a,
	0x06, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x42, 0x6f, 0x78, 0x52, 0x06, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x66, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x46, 0x61, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e,
	0x75, 0x6d, 0x5f, 0x66, 0x61, 0x63, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x6e, 0x75, 0x6d, 0x46, 0x61, 0x63, 0x65, 0x73, 0x22, 0xff, 0x01, 0x0a, 0x0a, 0x42, 0x53, 0x50,
	0x54, 0x65, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x5f, 0x61, 0x78, 0x69,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x52, 0x05, 0x73, 0x41, 0x78, 0x69,
	0x73, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x07, 0x73, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x06,
	0x74, 0x5f, 0x61, 0x78, 0x69, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x52,
	0x05, 0x74, 0x41, 0x78, 0x69, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x5f, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x74, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x78, 0x74, 0x5f,
	0x74, 0x65, 0x78, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6e,
	0x65, 0x78, 0x74, 0x54, 0x65, 0x78, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xd6, 0x01, 0x0a, 0x07, 0x42,
	0x53, 0x50, 0x46, 0x61, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x5f,
	0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x6e, 0x65,
	0x4e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x5f, 0x65, 0x64, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x45, 0x64, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x5f, 0x65, 0x64,
	0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x45, 0x64,
	0x67, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x78, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x65, 0x78, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x0a,
	0x0c, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x0b, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x22, 0xa4, 0x02, 0x0a, 0x07, 0x42, 0x53, 0x50, 0x4c, 0x65, 0x61, 0x66, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x2d, 0x0a, 0x06, 0x62, 0x6f, 0x75,
	0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x78,
	0x52, 0x06, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x5f, 0x6c, 0x65, 0x61, 0x66, 0x5f, 0x66, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0d, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4c, 0x65, 0x61, 0x66, 0x46, 0x61, 0x63, 0x65,
	0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x75, 0x6d, 0x5f, 0x6c, 0x65, 0x61, 0x66, 0x5f, 0x66, 0x61, 0x63,
	0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x6e, 0x75, 0x6d, 0x4c, 0x65, 0x61,
	0x66, 0x46, 0x61, 0x63, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f,
	0x6c, 0x65, 0x61, 0x66, 0x5f, 0x62, 0x72, 0x75, 0x73, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0e, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4c, 0x65, 0x61, 0x66, 0x42, 0x72, 0x75, 0x73, 0x68,
	0x12, 0x28, 0x0a, 0x10, 0x6e, 0x75, 0x6d, 0x5f, 0x6c, 0x65, 0x61, 0x66, 0x5f, 0x62, 0x72, 0x75,
	0x73, 0x68, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6e, 0x75, 0x6d, 0x4c,
	0x65, 0x61, 0x66, 0x42, 0x72, 0x75, 0x73, 0x68, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x07, 0x42, 0x53,
	0x50, 0x45, 0x64, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78, 0x31, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78, 0x32, 0x22, 0xbd, 0x01, 0x0a, 0x08, 0x42, 0x53,
	0x50, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x2d, 0x0a, 0x06, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x78, 0x52, 0x06, 0x62,
	0x6f, 0x75, 0x6e, 0x64, 0x73, 0x12, 0x29, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x12, 0x1b, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x66, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x46, 0x61, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6e, 0x75, 0x6d, 0x5f, 0x66, 0x61, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x6e, 0x75, 0x6d, 0x46, 0x61, 0x63, 0x65, 0x73, 0x22, 0x62, 0x0a, 0x08, 0x42, 0x53, 0x50,
	0x42, 0x72, 0x75, 0x73, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x73,
	0x69, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x53, 0x69, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x5f, 0x73, 0x69, 0x64, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x53, 0x69, 0x64, 0x65,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x45, 0x0a,
	0x0c, 0x42, 0x53, 0x50, 0x42, 0x72, 0x75, 0x73, 0x68, 0x53, 0x69, 0x64, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65,
	0x78, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x65, 0x78,
	0x69, 0x6e, 0x66, 0x6f, 0x22, 0x5f, 0x0a, 0x07, 0x42, 0x53, 0x50, 0x41, 0x72, 0x65, 0x61, 0x12,
	0x28, 0x0a, 0x10, 0x6e, 0x75, 0x6d, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x70, 0x6f, 0x72, 0x74,
	0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6e, 0x75, 0x6d, 0x41, 0x72,
	0x65, 0x61, 0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50,
	0x6f, 0x72, 0x74, 0x61, 0x6c, 0x22, 0x4d, 0x0a, 0x0d, 0x42, 0x53, 0x50, 0x41, 0x72, 0x65, 0x61,
	0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c,
	0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6f, 0x72, 0x74,
	0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x61,
	0x72, 0x65, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6f, 0x74, 0x68, 0x65, 0x72,
	0x41, 0x72, 0x65, 0x61, 0x22, 0x93, 0x07, 0x0a, 0x07, 0x42, 0x53, 0x50, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x2b, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x53, 0x50, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2f, 0x0a,
	0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x53, 0x50, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x2a,
	0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x53, 0x50, 0x50, 0x6c, 0x61,
	0x6e, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x08, 0x76, 0x65,
	0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x53, 0x50, 0x56, 0x65, 0x72, 0x74, 0x65,
	0x78, 0x52, 0x08, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x0a, 0x76,
	0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x53, 0x50, 0x56, 0x69,
	0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42,
	0x53, 0x50, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x37, 0x0a,
	0x0c, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42,
	0x53, 0x50, 0x54, 0x65, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x74, 0x65, 0x78, 0x74, 0x75,
	0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x27, 0x0a, 0x05, 0x66, 0x61, 0x63, 0x65, 0x73, 0x18,
	0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x42, 0x53, 0x50, 0x46, 0x61, 0x63, 0x65, 0x52, 0x05, 0x66, 0x61, 0x63, 0x65, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x29, 0x0a, 0x06, 0x6c,
	0x65, 0x61, 0x76, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x53, 0x50, 0x4c, 0x65, 0x61, 0x66, 0x52, 0x06,
	0x6c, 0x65, 0x61, 0x76, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x65, 0x61, 0x66, 0x5f, 0x66,
	0x61, 0x63, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x09, 0x6c, 0x65, 0x61, 0x66,
	0x46, 0x61, 0x63, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x65, 0x61, 0x66, 0x5f, 0x62, 0x72,
	0x75, 0x73, 0x68, 0x65, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x6c, 0x65, 0x61,
	0x66, 0x42, 0x72, 0x75, 0x73, 0x68, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x65, 0x64, 0x67, 0x65,
	0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x53, 0x50, 0x45, 0x64, 0x67, 0x65, 0x52, 0x05, 0x65, 0x64, 0x67, 0x65,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x75, 0x72, 0x66, 0x5f, 0x65, 0x64, 0x67, 0x65, 0x73, 0x18,
	0x10, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x73, 0x75, 0x72, 0x66, 0x45, 0x64, 0x67, 0x65, 0x73,
	0x12, 0x2a, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x18, 0x11, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x53, 0x50, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x2c, 0x0a, 0x07,
	0x62, 0x72, 0x75, 0x73, 0x68, 0x65, 0x73, 0x18, 0x12, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x53, 0x50, 0x42, 0x72, 0x75, 0x73,
	0x68, 0x52, 0x07, 0x62, 0x72, 0x75, 0x73, 0x68, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x0b, 0x62, 0x72,
	0x75, 0x73, 0x68, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x73, 0x18, 0x13, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x53, 0x50, 0x42, 0x72,
	0x75, 0x73, 0x68, 0x53, 0x69, 0x64, 0x65, 0x52, 0x0a, 0x62, 0x72, 0x75, 0x73, 0x68, 0x53, 0x69,
	0x64, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x70, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x70, 0x6f, 0x70, 0x12, 0x27, 0x0a, 0x05, 0x61, 0x72, 0x65, 0x61, 0x73, 0x18, 0x15,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x42, 0x53, 0x50, 0x41, 0x72, 0x65, 0x61, 0x52, 0x05, 0x61, 0x72, 0x65, 0x61, 0x73, 0x12, 0x3a,
	0x0a, 0x0c, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x73, 0x18, 0x16,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x42, 0x53, 0x50, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x52, 0x0b, 0x61,
	0x72, 0x65, 0x61, 0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x73, 0x22, 0x99, 0x01, 0x0a, 0x0b, 0x42,
	0x53, 0x50, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x08, 0x6d, 0x61,
	0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07,
	0x6d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x08,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x08, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x53, 0x50, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x42, 0x0b, 0x0a, 0x09,
	0x5f, 0x6d, 0x61, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x66, 0x6c, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x2f, 0x6c, 0x69, 0x62, 0x71, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bsp_proto_rawDescOnce sync.Once
	file_bsp_proto_rawDescData = file_bsp_proto_rawDesc
)

func file_bsp_proto_rawDescGZIP() []byte {
	file_bsp_proto_rawDescOnce.Do(func() {
		file_bsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_bsp_proto_rawDescData)
	})
	return file_bsp_proto_rawDescData
}

var file_bsp_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_bsp_proto_goTypes = []interface{}{
	(*Vector3)(nil),       // 0: proto.v1.Vector3
	(*BoundingBox)(nil),   // 1: proto.v1.BoundingBox
	(*BSPLump)(nil),       // 2: proto.v1.BSPLump
	(*BSPHeader)(nil),     // 3: proto.v1.BSPHeader
	(*BSPEntity)(nil),     // 4: proto.v1.BSPEntity
	(*BSPPlane)(nil),      // 5: proto.v1.BSPPlane
	(*BSPVertex)(nil),     // 6: proto.v1.BSPVertex
	(*BSPVisOffset)(nil),  // 7: proto.v1.BSPVisOffset
	(*BSPVisibility)(nil), // 8: proto.v1.BSPVisibility
	(*BSPNode)(nil),       // 9: proto.v1.BSPNode
	(*BSPTexInfo)(nil),    // 10: proto.v1.BSPTexInfo
	(*BSPFace)(nil),       // 11: proto.v1.BSPFace
	(*BSPLeaf)(nil),       // 12: proto.v1.BSPLeaf
	(*BSPEdge)(nil),       // 13: proto.v1.BSPEdge
	(*BSPModel)(nil),      // 14: proto.v1.BSPModel
	(*BSPBrush)(nil),      // 15: proto.v1.BSPBrush
	(*BSPBrushSide)(nil),  // 16: proto.v1.BSPBrushSide
	(*BSPArea)(nil),       // 17: proto.v1.BSPArea
	(*BSPAreaPortal)(nil), // 18: proto.v1.BSPAreaPortal
	(*BSPFile)(nil),       // 19: proto.v1.BSPFile
	(*BSPOverride)(nil),   // 20: proto.v1.BSPOverride
	nil,                   // 21: proto.v1.BSPEntity.PropertiesEntry
}
var file_bsp_proto_depIdxs = []int32{
	0,  // 0: proto.v1.BoundingBox.mins:type_name -> proto.v1.Vector3
	0,  // 1: proto.v1.BoundingBox.maxs:type_name -> proto.v1.Vector3
	2,  // 2: proto.v1.BSPHeader.lumps:type_name -> proto.v1.BSPLump
	21, // 3: proto.v1.BSPEntity.properties:type_name -> proto.v1.BSPEntity.PropertiesEntry
	0,  // 4: proto.v1.BSPPlane.normal:type_name -> proto.v1.Vector3
	0,  // 5: proto.v1.BSPVertex.point:type_name -> proto.v1.Vector3
	7,  // 6: proto.v1.BSPVisibility.offsets:type_name -> proto.v1.BSPVisOffset
	1,  // 7: proto.v1.BSPNode.bounds:type_name -> proto.v1.BoundingBox
	0,  // 8: proto.v1.BSPTexInfo.s_axis:type_name -> proto.v1.Vector3
	0,  // 9: proto.v1.BSPTexInfo.t_axis:type_name -> proto.v1.Vector3
	1,  // 10: proto.v1.BSPLeaf.bounds:type_name -> proto.v1.BoundingBox
	1,  // 11: proto.v1.BSPModel.bounds:type_name -> proto.v1.BoundingBox
	0,  // 12: proto.v1.BSPModel.origin:type_name -> proto.v1.Vector3
	3,  // 13: proto.v1.BSPFile.header:type_name -> proto.v1.BSPHeader
	4,  // 14: proto.v1.BSPFile.entities:type_name -> proto.v1.BSPEntity
	5,  // 15: proto.v1.BSPFile.planes:type_name -> proto.v1.BSPPlane
	6,  // 16: proto.v1.BSPFile.vertices:type_name -> proto.v1.BSPVertex
	8,  // 17: proto.v1.BSPFile.visibility:type_name -> proto.v1.BSPVisibility
	9,  // 18: proto.v1.BSPFile.nodes:type_name -> proto.v1.BSPNode
	10, // 19: proto.v1.BSPFile.texture_info:type_name -> proto.v1.BSPTexInfo
	11, // 20: proto.v1.BSPFile.faces:type_name -> proto.v1.BSPFace
	12, // 21: proto.v1.BSPFile.leaves:type_name -> proto.v1.BSPLeaf
	13, // 22: proto.v1.BSPFile.edges:type_name -> proto.v1.BSPEdge
	14, // 23: proto.v1.BSPFile.models:type_name -> proto.v1.BSPModel
	15, // 24: proto.v1.BSPFile.brushes:type_name -> proto.v1.BSPBrush
	16, // 25: proto.v1.BSPFile.brush_sides:type_name -> proto.v1.BSPBrushSide
	17, // 26: proto.v1.BSPFile.areas:type_name -> proto.v1.BSPArea
	18, // 27: proto.v1.BSPFile.area_portals:type_name -> proto.v1.BSPAreaPortal
	4,  // 28: proto.v1.BSPOverride.entities:type_name -> proto.v1.BSPEntity
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_bsp_proto_init() }
func file_bsp_proto_init() {
	if File_bsp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoundingBox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPLump); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPPlane); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPVertex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPVisOffset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPVisibility); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPTexInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPFace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPLeaf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPEdge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPBrush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPBrushSide); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPArea); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPAreaPortal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bsp_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSPOverride); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bsp_proto_msgTypes[20].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bsp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bsp_proto_goTypes,
		DependencyIndexes: file_bsp_proto_depIdxs,
		MessageInfos:      file_bsp_proto_msgTypes,
	}.Build()
	File_bsp_proto = out.File
	file_bsp_proto_rawDesc = nil
	file_bsp_proto_goTypes = nil
	file_bsp_proto_depIdxs = nil
}
